# -*- coding: utf-8 -*-
"""27-Feb-24 Assignemnt4-202301064

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMgKXJYOEhobvWm5M2_6_0WUXlX4aaKa
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('company_sales.csv')
print(data)

#line chart
plt.plot(data['total_profit'])
plt.show()

plt.plot(data['facecream'])
plt.plot(data['facewash'])
plt.plot(data['toothpaste'])
plt.plot(data['bathingsoap'])
plt.plot(data['shampoo'])
plt.plot(data['moisturizer'])

plt.show()

#bar chart
plt.bar(data['facecream'],data['facewash'])
plt.bar(data['toothpaste'],data['bathingsoap'])
plt.bar(data['shampoo'],data['moisturizer'])

plt.show()

#Plot scatter plot for 4 attributes from starting with different colours
import matplotlib.pyplot as plt
plt.scatter('facecream','facewash',color='b') #b is blue color

plt.scatter('toothpaste','bathingsoap',color='m') #m is magenta color

plt.show()